/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.CalculationRequest;
import io.swagger.model.CalculationResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-03-06T15:09:42.678Z")

@Api(value = "calculationRequest", description = "the calculationRequest API")
public interface CalculationRequestApi {

    @ApiOperation(value = "Calculations Swagger", nickname = "findCalculationsByStatus", notes = "Calculate interest with montant, duree and taux", response = CalculationResponse.class, tags={ "Calculation", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = CalculationResponse.class),
        @ApiResponse(code = 400, message = "Invalid status value") })
    @RequestMapping(value = "/calculationRequest",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<CalculationResponse> findCalculationsByStatus(@ApiParam(value = "Status values that need to be considered for filter" ,required=true )  @Valid @RequestBody CalculationRequest body);

}
